import { ArrowRight, CreditCard, Download, MoreVertical, Plus, ShieldCheck, WalletCards } from "lucide-react";
import PortalCard from "../../../components/client/portal/PortalCard";
import { transactions } from "../../../data/clientPortalData";

const ClientPayments = () => (
  <div className="mx-auto max-w-[1030px] p-5 sm:p-7">
    <div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><header><h1 className="text-3xl font-semibold tracking-[-0.03em]">Payments Management</h1><p className="mt-2 max-w-xl text-[#4c5261]">Overview of your financial activity, upcoming service invoices, and linked digital wallets.</p></header><div className="flex gap-3"><button className="flex items-center gap-2 rounded-lg border border-[#c5cad8] bg-white px-5 py-3" type="button"><Download className="size-4" /> Statement</button><button className="flex items-center gap-3 rounded-lg bg-[#0649ad] px-6 py-3 text-white" type="button">Pay Now <ArrowRight className="size-4" /></button></div></div>
    <div className="mt-7 grid gap-4 lg:grid-cols-3">
      <section className="rounded-xl bg-gradient-to-br from-[#0649ad] to-[#2861b3] p-6 text-white"><p className="uppercase tracking-[0.08em] text-[#c9d9ff]">Total Outstanding</p><strong className="mt-2 block text-4xl">৳ 12,450.00</strong><span className="mt-4 inline-block rounded-full bg-white/20 px-3 py-1 text-xs">ⓘ Due in 4 days</span><p className="mt-12 text-xs text-[#c9d9ff]">Last paid</p><p>Oct 12, 2024</p></section>
      <PortalCard className="p-6"><div className="flex justify-between"><span className="grid size-12 place-items-center rounded bg-pink-100 text-sm font-bold text-pink-600">bKash</span><ShieldCheck className="size-6 fill-emerald-400 text-emerald-500" /></div><h2 className="mt-5 font-semibold">Primary Wallet</h2><p className="text-[#4c5261]">017****5560</p><button className="mt-5 text-[#0649ad]" type="button">Manage ›</button></PortalCard>
      <PortalCard className="p-6"><div className="flex justify-between"><span className="grid size-12 place-items-center rounded bg-[#e7efff]"><CreditCard className="size-6 text-[#0649ad]" /></span><MoreVertical className="size-5" /></div><h2 className="mt-5 font-semibold">Visa ending in 4242</h2><p className="text-[#4c5261]">Expires 12/26</p><button className="mt-5 flex items-center gap-2 text-[#0649ad]" type="button">Add New Card <Plus className="size-4" /></button></PortalCard>
    </div>
    <PortalCard className="mt-5 overflow-hidden">
      <div className="flex gap-8 border-b border-[#c5cad8] px-6 pt-5"><button className="border-b-2 border-[#0649ad] pb-3 text-[#0649ad]" type="button">All History</button><button className="pb-3 text-[#4c5261]" type="button">Upcoming Invoices</button><button className="pb-3 text-[#4c5261]" type="button">Refunds</button></div>
      <div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left"><thead className="bg-[#eef2ff] text-sm text-[#4c5261]"><tr>{["Transaction ID","Service/Description","Date","Amount","Status","Actions"].map((heading) => <th className="px-6 py-4" key={heading}>{heading}</th>)}</tr></thead><tbody>{transactions.map((transaction) => <tr className="border-b border-[#c5cad8]" key={transaction.id}><td className="px-6 py-5">#{transaction.id}</td><td className="px-6 py-5 font-medium">{transaction.service}</td><td className="px-6 py-5 text-[#4c5261]">{transaction.date}</td><td className="px-6 py-5">{transaction.amount}</td><td className="px-6 py-5"><span className={`rounded-full px-3 py-1 text-[10px] font-semibold uppercase ${transaction.status === "Successful" ? "bg-[#9df2c8] text-emerald-700" : "bg-red-100 text-red-700"}`}>{transaction.status}</span></td><td className="px-6 py-5 text-[#0649ad]">{transaction.status === "Pending" ? "Pay Now" : "▤"}</td></tr>)}</tbody></table></div>
      <button className="w-full py-4 text-sm font-semibold text-[#0649ad]" type="button">View Full Transaction History⌄</button>
    </PortalCard>
    <section className="mt-7 flex flex-col gap-6 overflow-hidden rounded-3xl bg-[#005b4c] p-8 text-white sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-2xl font-semibold">Automate Your Healthcare Payments</h2><p className="mt-3 max-w-xl text-[#b5e8db]">Enable auto-debit via bKash or Credit Cards to ensure your loved ones never miss a care session due to pending payments.</p><button className="mt-6 rounded bg-[#a7ead8] px-6 py-3 font-medium text-[#06483d]" type="button">Enable Auto-Pay</button></div><WalletCards className="size-28 shrink-0 text-[#9ce1d1]" /></section>
  </div>
);

export default ClientPayments;
